### ISSUE TITLE
BUG: test_autolysis fails to import urlretreive in python3.5

### ISSUE THREAD

**Issue by skathirmani** [gramener/autolysis#6]
The script should handle the import for both python 2.7 and python 3.5. As of now it handles only python 2.7

```
======================================================================
ERROR: test_autolysis (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_autolysis
Traceback (most recent call last):
  File "C:\Anaconda3\lib\unittest\loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "e:\autolyse\autolysis\tests\test_autolysis.py", line 17, in <module>
    from urllib import urlretrieve
ImportError: cannot import name 'urlretrieve'


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
Makefile:46: recipe for target 'test' failed
make: *** [test] Error 1

```

**Comment by pratapvardhan** [comment]
Should have been fixed via 380fb0f , can you check on latest dev codebase?
